@startuml
'skinparam backgroundcolor transparent

skinparam package {
    backgroundcolor transparent
}


package "ControlMachine" {

    commandLine - [CLI]
    [CLI] --> [Processes] : {Variables, \nInventory}
    [Processes] ...> CLI : {results}
    [Processes] -> [Resources]
    [Processes] <. [Resources] : {hosts}

    [Processes] --> [Engine] : {Variables, \nInventory}
    [Engine] ..> Processes : {results}

    [Transport] .> [Engine] : {results}
    [Engine] --> [Transport] : {actionHandler}
}

 component [Resources] #GreenYellow
 component [Processes] #GreenYellow

package "RemoteMachine (1..*)" {

    protocol <-> [Module]

    [Transport] ---> protocol : {module}\n<<file>>
    [Transport] ---> protocol : {shell command}\n<<bytes>>
    protocol ...> [Transport] : {results}\n<<JSON>>
}

@enduml