@startuml

package "Ansible" {

    package "UI" {
        [CLI]
    }

    package "Infrastructure" {
        [Engine]
    }

    package "Utilities" as utilities{
        [Parsers]
        [Transport]
        [Configuration]
        [Loaders]
    }

    package "Extensions" as extensions {
        [Modules]
        [Plugins]
    }

    [CLI] <--> [Engine]
    [CLI] <-> [Configuration]
    [Configuration] <-> [Parsers]
    [Engine] <--> [Transport]
    [Engine] <---> [Modules]

    note bottom of Loaders: <b>Loaders</b> and <b>Plugins</b> are used almost everywhere
}

@enduml