@startuml

class Exception

Exception <|-- AssertionError
Exception <|--- AnsibleError
AssertionError <|-- AnsibleAssertionError
AnsibleError <|-- AnsibleAssertionError
AnsibleError <|-- AnsibleOptionsError
AnsibleError <|-- AnsibleRuntimeError
AnsibleError <|--  AnsibleParserError
AnsibleError <|-- AnsibleInternalError
AnsibleRuntimeError <|--- AnsibleModuleError
class AnsibleConnectionFailureError #greenyellow
AnsibleRuntimeError <|-- AnsibleConnectionFailureError
AnsibleRuntimeError <|--- AnsibleFilterError
AnsibleRuntimeError <|-- AnsibleLookupError
AnsibleRuntimeError <|--- AnsibleCallbackError
class AnsibleUndefinedVariable #greenyellow
AnsibleRuntimeError <|-- AnsibleUndefinedVariable
class AnsibleFileNotFoundError #greenyellow
AnsibleRuntimeError <|--- AnsibleFileNotFoundError
class AnsibleActionSkipError #greenyellow
AnsibleRuntimeError <|-- AnsibleActionSkipError
class AnsibleActionFailError #greenyellow
AnsibleRuntimeError <|--- AnsibleActionFailError

@enduml