@startuml

package "Ansible" {

    package "UI" {
        [CLI]
    }

    package "Infrastructure" {
        [Engine]
    }

    package "Utilities" {
        [Loaders]
        [Parsers]
        [Transport]
        [Configuration]
    }

    package "Extensions" {
        [Modules]
        [Plugins]
    }

    [CLI] <--> [Engine]
    [CLI] <-> [Configuration]
    [Configuration] <--> [Parsers]
    [CLI] <--> [Parsers]
    [Engine] <--> [Transport]
    [Transport] <---> [Plugins]
    [Engine] <--> [Modules]


    note as Note
     "This diagram sucks so far"
    end note
}

@enduml