@startuml

title Base CLI Configuration
package cli.CLI{
class CLI
}
package Configuration <<Rectangle>>{
package plugins{
    PluginLoader <|-- CLI
package inventory {
	InventoryManager <|-- CLI
}
package callback {
    CallbackModule <|-- CLI
}
}

package utils{
    Display <|-- CLI
}

package parsing{
    DataLoader <|-- CLI
}

package vars{
    VariableManager <|-- CLI
}

package python27.Lib {
	OptionParser <|-- CLI
}
}

@enduml

@startuml

title Additional Execution CLI Configuration

package cli.CLI{
    class AdhocCLI
    class PlaybookCLI
    class ConsoleCLI
}
package Configuration <<Rectangle>>{
package Playbook{
    Playbook <|-- AdhocCLI
    Playbook <|-- PlaybookCLI
    Play <|-- PlaybookCLI
    Play <|-- ConsoleCLI
    PlayContext <|-- PlaybookCLI
}
}
@enduml