@startuml

package plugins.connection {
	ConnectionBase <|-- ssh.Connection
	ConnectionBase <|-- winrm.Connection
	ConnectionBase <|-- docker.Connection
	ConnectionBase <|-- "*.Connection"
}

ConnectionBase : execute_command()
ConnectionBase : put_file()
ConnectionBase : fetch_file()
ConnectionBase : close()
ConnectionBase : _connect()

note "Ansible includes many\nadditional connection\nplugins (not pictured)" as N1

@enduml