@startuml

participant ConsoleCLI
create TaskQueueManager
ConsoleCLI -> TaskQueueManager: init(inventory, variable_manager, loader, options, passwords, stdout_callback, run_additional_callbacks, run_tree)
ConsoleCLI -> TaskQueueManager: run(play)
...
TaskQueueManager --> ConsoleCLI: result
@enduml

