@startuml

skinparam backgroundcolor transparent

package "Utilities Layer" {

    abstract Connection
    Connection : execute_command()
    Connection : put_file()
    Connection : fetch_file()
    Connection : close()
}

Package "CLI Layer" {
    class PlaybookCLI
}

note as n1
Inventory

  (YAML)
end note

n1..> PlaybookCLI

note as n2
Playbook

  (YAML)
end note

n2..> PlaybookCLI


Package "Infrastructure Layer"{

    abstract Playbook
    Playbook -> Play : run(host)
    PlaybookCLI --> Playbook : run()

    abstract Play
    Play -> Task : run()

    abstract Task
    Task -> Action : run()

    abstract Action
    Action --> Connection : put_file()
    Action --> Connection : execute_command()
    Action <.. Connection : response
}

@enduml
