@startuml

participant PlaybookCLI
participant Playbook #GreenYellow
loop for each playbook

create Playbook
PlaybookCLI -> Playbook: init(variable_manager, loader, options, passwords)
PlaybookCLI -> Playbook: run(playbook)

...
Playbook --> PlaybookCLI: result

end


@enduml

