@startuml

participant TaskExecutor
participant ActionBase
participant Connection
collections RemoteHost

TaskExecutor->ActionBase: run()

ActionBase->ActionBase: _configure_module()
ActionBase->Connection: put_file()

Connection->Connection: _connect()
Connection->RemoteHost: transfer module data

ActionBase->Connection: exec_command()
Connection->RemoteHost: run module remotely
ActionBase<--Connection: return response code, stdout, stderr

ActionBase->ActionBase: _parse_returned_data()
TaskExecutor<--ActionBase: return JSON

@enduml