@startuml

participant TaskExecutor
participant ActionBase
participant Connection
collections RemoteHost

TaskExecutor->ActionBase: run()

ActionBase->Connection: put_file()
Connection->RemoteHost: transfer module data
Connection<--RemoteHost: return remote path
ActionBase<--Connection: return remote path

ActionBase->Connection: exec_command()

Connection->RemoteHost: run module remotely
Connection<--RemoteHost: return response code, stdout, stderr

ActionBase<--Connection: return response code, stdout, stderr

TaskExecutor<--ActionBase: return JSON

@enduml