@startuml


file "not_yet_secrets.yml" as secrets {
    rectangle "secret-username: mikewhalen\nsecret-password: brony123"
}

rectangle "<&media-skip-forward> ansible-vault <&media-skip-forward>" as vault

file "secrets.yml" as encryptedSecrets {
    rectangle "secret-username: jfas)#3j5(!4oume][LkF\nsecret-password: 6*(%kljsdf8)39lkKOdjl"
}

file "playbook.yml" as playbook {
rectangle "username: {{secret-username}}\npassword: {{secret-password}}"
}

rectangle "<&media-skip-forward> ansible-playbook <&media-skip-forward>" as ansiblePlaybook
note bottom of ansiblePlaybook
    username: mikewhalen
    password: brony123
end note

secrets -> vault
vault --> encryptedSecrets
encryptedSecrets -> ansiblePlaybook
playbook --> ansiblePlaybook

@enduml