@startuml

title Ansible Adhoc CLI
actor User
User->ansible: main
ansible->AdhocCLI: parse()
ansible->AdhocCLI: run()
AdhocCLI->InventoryManager: list_hosts()
InventoryManager-->AdhocCLI: hostnames
AdhocCLI->Play: get_plays()
Play-->AdhocCLI: return plays
loop for all plays
    AdhocCLI->TaskQueueManager:run(play)
    TaskQueueManager->StrategyBase: run()
    StrategyBase->WorkerProcess: start()
    WorkerProcess->TaskExecuter: run()
    TaskExecuter->ActionModule: execute_module()
    ActionModule-->TaskExecuter: return data
    TaskExecuter-->WorkerProcess: return result
    StrategyBase->StrategyBase:process_results()
    StrategyBase-->TaskQueueManager: return result
    TaskQueueManager-> StrategyBase: cleanup()
    TaskQueueManager-->AdhocCLI: return play_return
end
AdhocCLI->TaskQueueManager: cleanup()
AdhocCLI-->ansible: return result
ansible-->User: return


@enduml