@startuml

participant AdHocCLI
participant Variables #GreenYellow
participant Inventory #GreenYellow
participant Playbook #GreenYellow

create Variables
AdHocCLI -> Variables: init(...)
Variables --> AdHocCLI
create Inventory
AdHocCLI -> Inventory: init(InventoryFile)
Inventory --> AdHocCLI
create Playbook
AdHocCLI -> Playbook: init(Variables, Inventory)
AdHocCLI -> Playbook: run()
...
Playbook --> AdHocCLI: result

@enduml

