@startuml

'skinparam backgroundcolor transparent

title Ansible Adhoc CLI
actor User
User->ansible: main
ansible->AdhocCLI: run()

participant Inventory #GreenYellow
participant Playbook #GreenYellow
AdhocCLI->Playbook: run()

Playbook->Inventory: list_hostgroup()
Inventory-->Playbook: return hostgroup

participant Play #GreenYellow
participant PlayExecutionStrategy #GreenYellow
participant ConcurrencyStrategy #GreenYellow


loop for all plays
    Playbook -> Play:run(play)
    Play -> PlayExecutionStrategy: run()
    PlayExecutionStrategy -> ConcurrencyStrategy: run()
    ConcurrencyStrategy -> WorkerProcess: run()

    participant Task #GreenYellow
    participant Action #GreenYellow

    WorkerProcess -> Task: run()
    Task -> Action: run()
    Action -> Connection: exec_command()
    entity RemoteMachine
    Connection -> RemoteMachine:run module remotely
    Connection <-- RemoteMachine: return response
    Action <-- Connection: return response
    Action --> Task: return data
    Task --> WorkerProcess: return result
    WorkerProcess --> ConcurrencyStrategy: return result
    ConcurrencyStrategy --> PlayExecutionStrategy: return result
    PlayExecutionStrategy->Play: return result
    Play->Playbook: return result

end
Playbook-->AdhocCLI: return result
AdhocCLI-->ansible: return result
ansible-->User: return


@enduml