@startuml
title ansible-vault create
actor User
User->ansible: ansible-vault create
participant "ansible"
"ansible"->VaultCLI: run()
VaultCLI-->DataLoader: run()
VaultCLI->DataLoader: setup_vault_secrets()
VaultCLI<--DataLoader: return()
VaultCLI-->User: input new_secret?
VaultCLI<--User: input new_secret
VaultCLI->VaultCLI: execute_encrypt()
VaultCLI->VaultCLI: execute_encrypt_string()
VaultCLI->VaultCLI: execute_create()
VaultCLI-->User: file.yaml

@enduml
