@startuml
title Ansible - Dry Run
User->ansible:ansible-playbook --check
ansible->PlaybookCLI: run()
PlaybookCLI->InventoryManager: list_hosts()
PlaybookCLI->PlayBookExecutor:run()
PlayBookExecutor->Playbook:load()
Playbook-->PlayBookExecutor: return Playbook
PlayBookExecutor->Playbook:get_plays(Playbook)
Playbook-->PlayBookExecutor: return plays
PlayBookExecutor->TaskQueueManager:run(play)
TaskQueueManager->PlayIterator: init()
PlayIterator-->TaskQueueManager: return iterator
TaskQueueManager->StrategyBase: run()
StrategyBase->WorkerProcess: start()
WorkerProcess->TaskExecuter: run()
TaskExecuter->ActionBase: run()
ActionBase-->TaskExecuter: return data
TaskExecuter-->WorkerProcess: return result
StrategyBase->StrategyBase:process_results()
StrategyBase-->TaskQueueManager: return result
TaskQueueManager-> StrategyBase: cleanup()
TaskQueueManager-->PlaybookCLI: return play_return
PlaybookCLI->TaskQueueManager: cleanup()
PlaybookCLI-->ansible: return result
ansible-->User: return

@enduml