@startuml
title Ansible - Dry Run

actor User
User->ansible:ansible-playbook --check
ansible->PlaybookCLI: run()
PlaybookCLI->InventoryManager: list_hosts()
PlaybookCLI->PlaybookExecutor:run()
PlaybookExecutor->Playbook:get_plays()
Playbook-->PlaybookExecutor: return plays
loop for all plays
    PlaybookExecutor->TaskQueueManager:run(play)
    entity RemoteMachine
    note right: Abstraction alert: \nThe TaskQueueManager \ndoesn't talk to the remote \nmachine directly by a long \nshot.
    TaskQueueManager->RemoteMachine
    RemoteMachine-->TaskQueueManager: return result
    TaskQueueManager-->PlaybookExecutor: return play_return
end
PlaybookExecutor->TaskQueueManager: cleanup()
PlaybookExecutor-->PlaybookCLI: return result
PlaybookCLI-->ansible: return result
ansible-->User: return

@enduml