@startuml
actor User
User->ansible: ansible-playbook --syntax-check
ansible->PlaybookCLI: run()
participant Playbook #GreenYellow
participant CheckSyntaxPlaybookExecutionStrategy #GreenYellow
participant Play #GreenYellow
PlaybookCLI->Playbook:run()
Playbook->CheckSyntaxPlaybookExecutionStrategy:run()
loop for all plays
    CheckSyntaxPlaybookExecutionStrategy->Play: post_validate()
    Play-->CheckSyntaxPlaybookExecutionStrategy: return bool
end
CheckSyntaxPlaybookExecutionStrategy --> Playbook: result
Playbook-->PlaybookCLI: return result
PlaybookCLI-->ansible: return result
ansible-->User: return
@enduml