@startuml
title Ansible - Syntax Check
User->ansible: ansible-playbook --syntax-check
ansible->PlaybookCLI: run()
PlaybookCLI->PlaybookExecutor:run()
PlaybookExecutor->Playbook:load()
Playbook-->PlaybookExecutor: return Playbook
PlaybookExecutor->Playbook:get_plays()
Playbook-->PlaybookExecutor: return plays
loop for all plays
PlaybookExecutor->Base: post_validate()
Base-->PlaybookExecutor: return bool
end
PlaybookExecutor-->PlaybookCLI: return result
PlaybookCLI-->ansible: return result
ansible-->User: return
@enduml