@startuml
skinparam backgroundcolor transparent

participant TaskQueueManager
create StrategyBase
TaskQueueManager->StrategyBase: init() via loader
TaskQueueManager->StrategyBase: run()
create WorkerProcess
StrategyBase->WorkerProcess: init()
StrategyBase->WorkerProcess: run()
note left: Abstraction alert: StrategyBase grabs \na WorkerProcess from a thread pool
create TaskExecutor
WorkerProcess->TaskExecutor: init()
WorkerProcess->TaskExecutor: run()
participant ActionBase
create Connection
TaskExecutor->Connection: init() via loader
create ActionBase
TaskExecutor->ActionBase: init() via loader
TaskExecutor->ActionBase: run()
ActionBase -> Connection: exec_command()
entity RemoteMachine
Connection->RemoteMachine:run module remotely
Connection <-- RemoteMachine: return response
ActionBase <-- Connection: return response
ActionBase-->TaskExecutor: return data
TaskExecutor-->WorkerProcess: return result
destroy TaskExecutor
WorkerProcess-->StrategyBase: return result
note right: Abstraction alert: The WorkerProcess result \nactually returns via the thread pool
StrategyBase-->TaskQueueManager: return result
@enduml