@startuml

participant CLI
create Display
CLI -> Display: init(..)
CLI -> Display: verbose("message one")
entity Console
Display -> Console: display("message one", stderr:False)
CLI -> Display: warning("message two")
Display -> Console: display("message two", stderr:True)
@enduml