@startuml
participant CLI
create InventoryManager
CLI -> InventoryManager: init(loader,source)
create InventoryData
InventoryManager->InventoryData: init()
InventoryManager<--InventoryData: return
InventoryManager->InventoryManager: parse_source()
CLI <-- InventoryManager: return
CLI -> InventoryManager: list_hosts(patterns)
CLI <-- InventoryManager: return hosts

@enduml