@startuml
participant CLI
participant Variables #greenYellow
create Variables
CLI -> Variables: init(inventoryFile)
CLI -> Variables: load_extra_vars(extraVariablesFiles)
loop for each extraVariablesFile in extraVariablesFiles
Variables -> DataLoader: load_from_file(extraVariablesFile)
DataLoader -> DataLoader: read vars from YAML file
Variables <-- DataLoader: return parsed_data
end loop
CLI <-- Variables: return extra_vars

CLI -> Variables: load_options_vars(options)
CLI <-- Variables: return options_vars

@enduml