@startuml
participant CLI
create VariableManager
CLI -> VariableManager: init(loader,inventory)
CLI -> VariableManager: load_extra_vars(loader, options)
loop for each extra_var in options
VariableManager -> DataLoader: load_from_file(extra_var)
DataLoader -> DataLoader: read vars from YAML file
VariableManager <-- DataLoader: return parsed_data
end loop
CLI <-- VariableManager: return extra_vars()

CLI -> VariableManager: load_options_vars(options)
CLI <-- VariableManager: return options_vars

@enduml